language: node_js
node_js:
  - "6"
  - "6.1"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn
  - yarn global add gulp
cache:
  directories:
  - $HOME/.cache/yarn